### ISSUE TITLE
Preview site link not working

### ISSUE THREAD

**Issue by nirban256** [bradtraversy/github-finder-app#1]
The hosted link of the website is not working, showing Error 404 , Page not found

**Comment by decoded-cipher** [comment]
> The hosted link of the website is not working, showing Error 404 , Page not found

Check the link under **Environments.**
This link will work: **https://github-finder-app-2h5gc942c-bradtraversy.vercel.app/**

**Comment by dmytrodubinin** [comment]
> > The hosted link of the website is not working, showing Error 404 , Page not found
> 
> Check the link under **Environments.** This link will work: **https://github-finder-app-2h5gc942c-bradtraversy.vercel.app/**

App does not work by this link (search by name do nothing)
